version: 2.1

# Define the jobs we want to run for this project
jobs:
  plan:
    docker:
      - image: febus982/terraform-foundation:latest
    steps:
      - checkout
#  test:
#    docker:
#      - image: circleci/<language>:<version TAG>
#    steps:
#      - checkout
#      - run: my-test-commands
#  deploy:
#    docker:
#      - image: circleci/<language>:<version TAG>
#    steps:
#      - checkout
#      - run: my-deploy-commands

# Orchestrate our job run sequence
workflows:
  plan:
    jobs:
      - plan
#      - test:
#          requires:
#            - build
#      - hold:
#          type: approval
#          requires:
#            - build
#            - test
#      - deploy:
#          requires:
#            - hold